### ISSUE TITLE
Reload Specification loading crashes

### ISSUE THREAD

**Issue by Razman221** [Leviathan143/minecraft-quiverbow#6]
Hello, I am new to GitHub and know very little about coding, so I apologize if I am not following the guidelines regarding posting an issue. I do have a crash report however with version b102. 

I am running multiple mods and will edit this issue after I go through them 1 by 1 to see which mod is causing the conflict, if any.

[crash-2020-12-04_13.06.20-client.txt](https://github.com/Daomephsta/quiverbow-restrung/files/5645410/crash-2020-12-04_13.06.20-client.txt)

**Comment by Razman221** [comment]
I took out all the mods except for quiverbow_restrung, and the game still crashed. Here's the most recent crash report.

[crash-2020-12-04_14.57.14-client.txt](https://github.com/Daomephsta/quiverbow-restrung/files/5645432/crash-2020-12-04_14.57.14-client.txt)

**Comment by Daomephsta** [comment]
This bug is possibly specific to Oracle JREs; or to Oracle JRE 1.8.0u51, the JRE Minecraft bundles. 
It doesn't occur with the AdoptOpenJDK JDKs and JREs I use.

I'll see what I can do about this, getting Oracle JDKs or JREs is more of a pain than it used to be. In the meantime, you can solve this issue by [Using non-Oracle Java](https://minecraft.gamepedia.com/Tutorials/Update_Java). I recommend AdoptOpenJDK, as that's known to avoid this bug.

**Comment by Daomephsta** [comment]
Wrong issue number
