### ISSUE TITLE
Arms assistant causing crashes (due to rendering maybe?) [Bug]

### ISSUE THREAD

**Issue by BarBreaker** [Leviathan143/minecraft-quiverbow#7]
Full log is here: https://paste.ee/p/Qi9Ma

Attempting to use the Arms Assistant causes crashes, this isn't a new issue, though I'm pretty sure it bounced between fixed and broken again several times on the Domochevsky releases. I'm not sure exactly how those crashes occurred there so this might be distinct.

System details: Intel i5 7th gen, 4GB ram min 11GB ram max (it's server and host running on the same machine so I need the extra RAM), Intel integrated Graphics 620 chipset. It's possible that integrated graphics are the issue, but I've never had any issue before.

**Comment by Daomephsta** [comment]
This bug was caused by a change in Java 9 that isn't binary compatible with Java 8. Due to the nature of the change, the source is Java 8 compatible, however compiling with Java 9 or greater results in a binary that is incompatible with Java 8. I've setup the buildscript to force use of Java 8 when compiling, so this kind of bizarre issue can't happen again. 

If you wish to use Arms Assistants before the next release, updating to Java 9 or later will allow you to use the existing releases. Do be aware that they're still a bit buggy due being completely rewritten. The next release will fix several of those bugs, as well as adding in-game documentation via Patchouli.
